language: cpp
compiler:
  - gcc

branches:
  only:
    - travis-ci

before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libqt4-dev qt4-dev-tools

script: ldd -r /tmp/CTK-Superbuild-Release-experimental/CMakeExternals/Install/bin/storescu && chrpath -l /tmp/CTK-Superbuild-Release-experimental/CMakeExternals/Install/bin/storescu && ls -l /tmp/CTK-Superbuild-Release-experimental/CMakeExternals/Install/lib && ctest -S ./CMake/ctkTravisDashboardScript.cmake
