language: cpp
compiler:
  - gcc

branches:
  only:
    - travis-ci

before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libqt4-dev libqt4-sql-sqlite

script: ctest -VV -S ./CMake/ctkTravisDashboardScript.cmake
