language: cpp

compiler:
  - gcc

env: DISPLAY=:9

branches:
  only:
    - travis-ci

before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake chrpath
  - sudo apt-get install -y libqt4-dev qt4-dev-tools
  - sudo apt-get install -y xpra xserver-xorg-video-dummy

before_script: xpra --xvfb="Xorg +extension GLX -config `pwd`/Applications/Testing/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log"  start :9

script: ctest -V -S ./CMake/ctkTravisDashboardScript.cmake

after_script:
  - xpra stop :9
  - ldd -r /tmp/CTK-Superbuild-Release-experimental/CMakeExternals/Install/bin/storescu
  - chrpath -l /tmp/CTK-Superbuild-Release-experimental/CMakeExternals/Install/bin/storescu
  - "cat ~/.xpra/*"
