language: cpp

compiler:
  - gcc

branches:
  only:
    - travis-ci

env: DISPLAY=:9 LD_LIBRARY_PATH=/tmp/CTK-Superbuild-Release-experimental/CMakeExternals/Install/lib

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y chrpath libqt4-dev qt4-dev-tools libvtk5-dev
  - sudo apt-get install -y xpra xserver-xorg-video-dummy

before_script:
  - wget -P /tmp http://www.cmake.org/files/v2.8/cmake-2.8.9.tar.gz
  - tar xz -C /tmp -f /tmp/cmake-2.8.9.tar.gz
  - cd /tmp/cmake-2.8.9 && ./configure --prefix=/usr/local
  - cd /tmp/cmake-2.8.9 && make -j4 install
  - xpra --xvfb="Xorg +extension GLX -config `pwd`/Applications/Testing/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log"  start :9

script: ctest -V -S ./CMake/ctkTravisDashboardScript.cmake

after_script:
  - xpra stop :9
  - cat /tmp/CTK-Superbuild-Release-experimental/DCMTK-build/CMakeCache.txt
  - "cat ~/.xpra/*"
