language: cpp
compiler:
  - gcc

env:
  - QT_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/qt4/plugins

branches:
  only:
    - travis-ci

before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libqt4-dev qt4-dev-tools

script: ls -l $QT_PLUGIN_PATH && ls -l $QT_PLUGIN_PATH/sqldrivers && qmake --version && cmake -version
#script: ctest -VV -S ./CMake/ctkTravisDashboardScript.cmake
