language: cpp
compiler:
  - gcc

branches:
  only:
    - travis-ci

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libqt4-dev libdcmtk2-dev libinsighttoolkit3-dev

script: ctest -VV -S ./CMake/ctkTravisDashboardScript.cmake
