language: cpp
compiler:
  - gcc

branches:
  only:
    - travis-ci

before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake chrpath
  - sudo apt-get install -y libqt4-dev qt4-dev-tools

script: ctest -S ./CMake/ctkTravisDashboardScript.cmake
